--- 

version: '3'

services:
  essential-photo:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/opt/essential-photo
    tmpfs:
      - /tmp/pids
    ports:
      - '3001:3001'

    environment:
      DB_HOST: localhost
      DB_NAME: essential_photo_backend_development
      DB_USER: postgres
      DB_PASSWORD: password
      PIDFILE: /tmp/pids/server.pid

    command: bin/rails s -p 3001 --binding 0.0.0.0
    entrypoint: ["/opt/essential-photo/docker-entrypoint.sh"]
    
  db:
    image: postgres:14.7-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: essential_photo_backend_development
      POSTGRES_PASSWORD: password
    volumes: 
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
networks:
  default:
    name: local_network
