
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: essential_photo_backend_development

test:
  <<: *default
  database: essential_photo_backend_test


production:
  <<: *default
  database: essential_photo_backend_production
